---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for IAM roles and policy for prod Environment
Resources:
  prodEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prodEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Tags:
      - Key: Name
        Value: prodEC2Role
      - Key: Environment
        Value: prod
  prodEksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prodEksClusterRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Tags:
      - Key: Name
        Value: prodEksClusterRole
      - Key: Environment
        Value: prod
  prodEksNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prodEksNodeGroupRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      Policies:
      - PolicyName: EBSCSIDriver
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:CreateSnapshot
            - ec2:CreateTags
            - ec2:CreateVolume
            - ec2:DeleteSnapshot
            - ec2:DeleteTags
            - ec2:DeleteVolume
            - ec2:DescribeInstances
            - ec2:DescribeSnapshots
            - ec2:DescribeTags
            - ec2:DescribeVolumes
            - ec2:DetachVolume
            Resource: "*"
      - PolicyName: ClusterAutoscaler
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:DescribeAutoScalingInstances
            - autoscaling:DescribeLaunchConfigurations
            - autoscaling:DescribeTags
            - autoscaling:SetDesiredCapacity
            - autoscaling:TerminateInstanceInAutoScalingGroup
            - ec2:DescribeLaunchTemplateVersions
            Resource: "*"
            Effect: Allow
      - PolicyName: S3PowerUser
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
            - s3:PutAnalyticsConfiguration
            - s3:GetObjectVersionTagging
            - s3:GetObjectAcl
            - s3:GetBucketObjectLockConfiguration
            - s3:GetObjectVersionAcl
            - s3:DeleteObject
            - s3:GetBucketPolicyStatus
            - s3:GetObjectRetention
            - s3:GetBucketWebsite
            - s3:PutObjectLegalHold
            - s3:GetObjectLegalHold
            - s3:GetBucketNotification
            - s3:PutBucketCORS
            - s3:GetReplicationConfiguration
            - s3:ListMultipartUploadParts
            - s3:PutObject
            - s3:GetObject
            - s3:GetAnalyticsConfiguration
            - s3:PutBucketObjectLockConfiguration
            - s3:GetObjectVersionForReplication
            - s3:GetLifecycleConfiguration
            - s3:GetInventoryConfiguration
            - s3:GetBucketTagging
            - s3:PutAccelerateConfiguration
            - s3:DeleteObjectVersion
            - s3:GetBucketLogging
            - s3:ListBucketVersions
            - s3:RestoreObject
            - s3:ListBucket
            - s3:GetAccelerateConfiguration
            - s3:GetBucketPolicy
            - s3:PutEncryptionConfiguration
            - s3:GetEncryptionConfiguration
            - s3:GetObjectVersionTorrent
            - s3:AbortMultipartUpload
            - s3:GetBucketRequestPayment
            - s3:GetObjectTagging
            - s3:GetMetricsConfiguration
            - s3:PutBucketVersioning
            - s3:GetBucketPublicAccessBlock
            - s3:ListBucketMultipartUploads
            - s3:GetBucketVersioning
            - s3:GetBucketAcl
            - s3:PutInventoryConfiguration
            - s3:GetObjectTorrent
            - s3:PutBucketRequestPayment
            - s3:PutObjectRetention
            - s3:GetBucketCORS
            - s3:GetBucketLocation
            - s3:GetObjectVersion
            Resource: "*"
  prodEksmngNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prodEksmngNodeGroupRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      Policies:
      - PolicyName: EBSCSIDrivers
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:CreateSnapshot
            - ec2:CreateTags
            - ec2:CreateVolume
            - ec2:DeleteSnapshot
            - ec2:DeleteTags
            - ec2:DeleteVolume
            - ec2:DescribeInstances
            - ec2:DescribeSnapshots
            - ec2:DescribeTags
            - ec2:DescribeVolumes
            - ec2:DetachVolume
            Resource: "*"
      - PolicyName: ClusterAutoscalers
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:DescribeAutoScalingInstances
            - autoscaling:DescribeLaunchConfigurations
            - autoscaling:DescribeTags
            - autoscaling:SetDesiredCapacity
            - autoscaling:TerminateInstanceInAutoScalingGroup
            - ec2:DescribeLaunchTemplateVersions
            Resource: "*"
            Effect: Allow
      - PolicyName: S3PowerUsers
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
            - s3:PutAnalyticsConfiguration
            - s3:GetObjectVersionTagging
            - s3:GetObjectAcl
            - s3:GetBucketObjectLockConfiguration
            - s3:GetObjectVersionAcl
            - s3:DeleteObject
            - s3:GetBucketPolicyStatus
            - s3:GetObjectRetention
            - s3:GetBucketWebsite
            - s3:PutObjectLegalHold
            - s3:GetObjectLegalHold
            - s3:GetBucketNotification
            - s3:PutBucketCORS
            - s3:GetReplicationConfiguration
            - s3:ListMultipartUploadParts
            - s3:PutObject
            - s3:GetObject
            - s3:GetAnalyticsConfiguration
            - s3:PutBucketObjectLockConfiguration
            - s3:GetObjectVersionForReplication
            - s3:GetLifecycleConfiguration
            - s3:GetInventoryConfiguration
            - s3:GetBucketTagging
            - s3:PutAccelerateConfiguration
            - s3:DeleteObjectVersion
            - s3:GetBucketLogging
            - s3:ListBucketVersions
            - s3:RestoreObject
            - s3:ListBucket
            - s3:GetAccelerateConfiguration
            - s3:GetBucketPolicy
            - s3:PutEncryptionConfiguration
            - s3:GetEncryptionConfiguration
            - s3:GetObjectVersionTorrent
            - s3:AbortMultipartUpload
            - s3:GetBucketRequestPayment
            - s3:GetObjectTagging
            - s3:GetMetricsConfiguration
            - s3:PutBucketVersioning
            - s3:GetBucketPublicAccessBlock
            - s3:ListBucketMultipartUploads
            - s3:GetBucketVersioning
            - s3:GetBucketAcl
            - s3:PutInventoryConfiguration
            - s3:GetObjectTorrent
            - s3:PutBucketRequestPayment
            - s3:PutObjectRetention
            - s3:GetBucketCORS
            - s3:GetBucketLocation
            - s3:GetObjectVersion
            Resource: "*"
Outputs:
  prodEC2RoleArn:
    Description: Arn of prodEC2Role Iam role
    Value:
      Fn::GetAtt:
      - prodEC2Role
      - Arn
  prodEksClusterRoleArn:
    Description: Arn of prodEksClusterRole Iam role
    Value:
      Fn::GetAtt:
      - prodEksClusterRole
      - Arn
  prodEksNodeGroupRoleArn:
    Description: Arn of prodEksNodeGroupRole Iam role
    Value:
      Fn::GetAtt:
      - prodEksNodeGroupRole
      - Arn
  prodEksmngNodeGroupRoleArn:
    Description: Arn of prodEksmngNodeGroupRole Iam role
    Value:
      Fn::GetAtt:
      - prodEksmngNodeGroupRole
      - Arn